### PR TITLE
Pep8 python3

### PR DESCRIPTION
**Pull request by amueller**
This PR does more standard formatting and Python3 support.
I didn't test with Python2 but I think it should still work.

### CODE REVIEW

**Comment by amueller** [comment]
I'm a bit confused by this line: https://github.com/bmtgoncalves/Mining-Georeferenced-Data/blob/master/SurgePrediction_Live/MultiLayerSurgePrediction.py#L145
The point that are labelled 1.0 are used for training, but not evaluated in prediction.

**Comment by tnoulas** [comment]
Andrews thanks so much for your feedback.
Actually, I do something worse as I was just let by another attendee:
In the following lines 148-149 I effectively leak testing data to the
model!

The merits of democratising your code :).

We have a paper under submission on this, so that has been a life saver
amidst a little embarassing. The supervised learning results are not that
spectacular, but still the argument for using multiple data layers stays
valid (phew :). )

**Comment by amueller** [comment]
`cross_val_predict(model, X_train, y_train, cv=LeaveOneOut(len(X_train))`
Should be a good way to do the thing (possibly more savely).

**Comment by amueller** [comment]
all the whitespace fixes are a bit of a nitpick (done by autopep8) and if you want I can send a PR only containing the python3 fixes.

**Comment by amueller** [comment]
(also I don't think it's embarrassing. Everybody's code has bugs, you were brave enough to open your code up to criticism ;)
A good reason to use library functions even for something as "simple" as cross-validation is that it is actually easy to mess up. I hope we can make it more usable.

**Comment by bmtgoncalves** [comment]
Thank you for the PR. I'm pretty picky about PEP8 compliance as well (have a plugin on subl to warn me when there's an issue).

**Comment by tnoulas** [comment]
Hi Andreas,

I have trying to use the above code for cross_validation but it is not easy
to find how to import the function appropriately. I am looking at this
example:
http://scikit-learn.org/stable/auto_examples/plot_cv_predict.html

This is what I am getting when trying to import through the interpreter.

> > > from sklearn.cross_validation import cross_val_predict
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name cross_val_predict
> > > 
> > > import sklearn.cross_validation

best,
tassos

**Comment by amueller** [comment]
You can find how to import it in the API docs:
http://scikit-learn.org/stable/modules/classes.html
This document contains all classes and functions and where to find them.

and see here:
http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.cross_val_predict.html#sklearn.cross_validation.cross_val_predict

`cross_val_predict` was introduced in 0.16, so it is likely that you have an older version. We are now at 0.17 btw.

**Pull request merged**
